"""
DualTwin Technologies 360° - Common Utilities

This module provides shared helper functions for simulations, plotting, logging,
and data generation used across all concept modules.
"""

import json
import logging
import random
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('dualtwin')


# =============================================================================
# Data Classes for Digital Twin Components
# =============================================================================

@dataclass
class SensorReading:
    """Represents a single sensor reading from a physical asset."""
    sensor_id: str
    timestamp: datetime
    value: float
    unit: str
    quality: float = 1.0  # Data quality score 0-1
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'sensor_id': self.sensor_id,
            'timestamp': self.timestamp.isoformat(),
            'value': self.value,
            'unit': self.unit,
            'quality': self.quality
        }


@dataclass
class TwinState:
    """Represents the current state of a digital twin."""
    twin_id: str
    timestamp: datetime
    properties: Dict[str, Any] = field(default_factory=dict)
    status: str = "active"
    health_score: float = 1.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'twin_id': self.twin_id,
            'timestamp': self.timestamp.isoformat(),
            'properties': self.properties,
            'status': self.status,
            'health_score': self.health_score
        }
    
    def update_property(self, key: str, value: Any) -> None:
        """Update a single property of the twin."""
        self.properties[key] = value
        self.timestamp = datetime.now()


@dataclass
class Alert:
    """Represents an alert generated by the digital twin system."""
    alert_id: str
    twin_id: str
    timestamp: datetime
    severity: str  # 'info', 'warning', 'critical'
    message: str
    source: str
    acknowledged: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'alert_id': self.alert_id,
            'twin_id': self.twin_id,
            'timestamp': self.timestamp.isoformat(),
            'severity': self.severity,
            'message': self.message,
            'source': self.source,
            'acknowledged': self.acknowledged
        }


# =============================================================================
# Simulation Utilities
# =============================================================================

class SensorSimulator:
    """Simulates sensor data streams for digital twin demonstrations."""
    
    def __init__(
        self,
        sensor_id: str,
        base_value: float,
        noise_level: float = 0.1,
        drift_rate: float = 0.001,
        unit: str = "units"
    ):
        self.sensor_id = sensor_id
        self.base_value = base_value
        self.noise_level = noise_level
        self.drift_rate = drift_rate
        self.unit = unit
        self.current_drift = 0.0
        self.reading_count = 0
    
    def generate_reading(self) -> SensorReading:
        """Generate a single sensor reading with noise and drift."""
        self.reading_count += 1
        self.current_drift += random.gauss(0, self.drift_rate)
        
        noise = random.gauss(0, self.noise_level * self.base_value)
        value = self.base_value + self.current_drift + noise
        
        quality = max(0.0, min(1.0, 1.0 - abs(noise) / (self.base_value * 0.5)))
        
        return SensorReading(
            sensor_id=self.sensor_id,
            timestamp=datetime.now(),
            value=value,
            unit=self.unit,
            quality=quality
        )
    
    def generate_stream(self, count: int, interval_seconds: float = 1.0) -> List[SensorReading]:
        """Generate a stream of sensor readings."""
        readings = []
        base_time = datetime.now()
        
        for i in range(count):
            reading = self.generate_reading()
            reading.timestamp = base_time + timedelta(seconds=i * interval_seconds)
            readings.append(reading)
        
        return readings
    
    def reset(self) -> None:
        """Reset the simulator state."""
        self.current_drift = 0.0
        self.reading_count = 0


class PhysicsModel:
    """Simple physics model for simulating physical system behavior."""
    
    def __init__(self, model_type: str = "thermal"):
        self.model_type = model_type
        self.state = {}
    
    def thermal_model(
        self,
        current_temp: float,
        ambient_temp: float,
        heat_input: float,
        thermal_mass: float = 100.0,
        heat_transfer_coeff: float = 0.1,
        dt: float = 1.0
    ) -> float:
        """
        Simple thermal model: dT/dt = (Q_in - h*(T - T_ambient)) / C
        
        Args:
            current_temp: Current temperature
            ambient_temp: Ambient temperature
            heat_input: Heat input (W)
            thermal_mass: Thermal mass/capacity (J/K)
            heat_transfer_coeff: Heat transfer coefficient (W/K)
            dt: Time step (s)
        
        Returns:
            New temperature after time step
        """
        heat_loss = heat_transfer_coeff * (current_temp - ambient_temp)
        temp_change = (heat_input - heat_loss) / thermal_mass * dt
        return current_temp + temp_change
    
    def mechanical_model(
        self,
        position: float,
        velocity: float,
        force: float,
        mass: float = 1.0,
        friction: float = 0.1,
        dt: float = 0.01
    ) -> Tuple[float, float]:
        """
        Simple mechanical model: F = ma with friction
        
        Args:
            position: Current position
            velocity: Current velocity
            force: Applied force
            mass: Object mass
            friction: Friction coefficient
            dt: Time step
        
        Returns:
            Tuple of (new_position, new_velocity)
        """
        friction_force = -friction * velocity
        acceleration = (force + friction_force) / mass
        new_velocity = velocity + acceleration * dt
        new_position = position + new_velocity * dt
        return new_position, new_velocity
    
    def fluid_flow_model(
        self,
        inlet_pressure: float,
        outlet_pressure: float,
        pipe_resistance: float = 1.0
    ) -> float:
        """
        Simple fluid flow model: Q = (P_in - P_out) / R
        
        Args:
            inlet_pressure: Inlet pressure
            outlet_pressure: Outlet pressure
            pipe_resistance: Flow resistance
        
        Returns:
            Flow rate
        """
        return (inlet_pressure - outlet_pressure) / pipe_resistance


# =============================================================================
# Data Processing Utilities
# =============================================================================

def readings_to_dataframe(readings: List[SensorReading]) -> pd.DataFrame:
    """Convert a list of sensor readings to a pandas DataFrame."""
    data = [r.to_dict() for r in readings]
    df = pd.DataFrame(data)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    return df


def calculate_statistics(values: List[float]) -> Dict[str, float]:
    """Calculate basic statistics for a list of values."""
    arr = np.array(values)
    return {
        'mean': float(np.mean(arr)),
        'std': float(np.std(arr)),
        'min': float(np.min(arr)),
        'max': float(np.max(arr)),
        'median': float(np.median(arr)),
        'count': len(values)
    }


def detect_anomalies(
    values: List[float],
    threshold_std: float = 2.0
) -> List[Tuple[int, float]]:
    """
    Detect anomalies using simple statistical method.
    
    Args:
        values: List of values to analyze
        threshold_std: Number of standard deviations for anomaly threshold
    
    Returns:
        List of (index, value) tuples for detected anomalies
    """
    arr = np.array(values)
    mean = np.mean(arr)
    std = np.std(arr)
    
    anomalies = []
    for i, v in enumerate(values):
        if abs(v - mean) > threshold_std * std:
            anomalies.append((i, v))
    
    return anomalies


def moving_average(values: List[float], window: int = 5) -> List[float]:
    """Calculate moving average of values."""
    if len(values) < window:
        return values
    
    result = []
    for i in range(len(values)):
        start = max(0, i - window + 1)
        result.append(sum(values[start:i+1]) / (i - start + 1))
    
    return result


# =============================================================================
# Visualization Utilities
# =============================================================================

def create_twin_comparison_data(
    physical_values: List[float],
    twin_values: List[float],
    timestamps: Optional[List[datetime]] = None
) -> pd.DataFrame:
    """Create a DataFrame for comparing physical and twin values."""
    if timestamps is None:
        timestamps = [datetime.now() + timedelta(seconds=i) for i in range(len(physical_values))]
    
    return pd.DataFrame({
        'timestamp': timestamps,
        'physical': physical_values,
        'twin': twin_values,
        'difference': [p - t for p, t in zip(physical_values, twin_values)]
    })


def format_value(value: float, unit: str, precision: int = 2) -> str:
    """Format a value with its unit for display."""
    return f"{value:.{precision}f} {unit}"


# =============================================================================
# Logging and Monitoring Utilities
# =============================================================================

class TwinLogger:
    """Logger specifically for digital twin operations."""
    
    def __init__(self, twin_id: str, log_file: Optional[str] = None):
        self.twin_id = twin_id
        self.logger = logging.getLogger(f'dualtwin.{twin_id}')
        self.events: List[Dict[str, Any]] = []
        
        if log_file:
            handler = logging.FileHandler(log_file)
            handler.setFormatter(logging.Formatter(
                '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            ))
            self.logger.addHandler(handler)
    
    def log_state_update(self, old_state: Dict, new_state: Dict) -> None:
        """Log a state update event."""
        event = {
            'type': 'state_update',
            'timestamp': datetime.now().isoformat(),
            'twin_id': self.twin_id,
            'old_state': old_state,
            'new_state': new_state
        }
        self.events.append(event)
        self.logger.info(f"State updated: {old_state} -> {new_state}")
    
    def log_alert(self, alert: Alert) -> None:
        """Log an alert event."""
        event = {
            'type': 'alert',
            'timestamp': datetime.now().isoformat(),
            'twin_id': self.twin_id,
            'alert': alert.to_dict()
        }
        self.events.append(event)
        log_method = getattr(self.logger, alert.severity, self.logger.info)
        log_method(f"Alert: {alert.message}")
    
    def log_sync(self, source: str, data_points: int) -> None:
        """Log a synchronization event."""
        event = {
            'type': 'sync',
            'timestamp': datetime.now().isoformat(),
            'twin_id': self.twin_id,
            'source': source,
            'data_points': data_points
        }
        self.events.append(event)
        self.logger.info(f"Synced {data_points} data points from {source}")
    
    def get_events(self, event_type: Optional[str] = None) -> List[Dict[str, Any]]:
        """Get logged events, optionally filtered by type."""
        if event_type:
            return [e for e in self.events if e['type'] == event_type]
        return self.events


# =============================================================================
# Configuration Utilities
# =============================================================================

def load_config(config_path: str) -> Dict[str, Any]:
    """Load configuration from a YAML or JSON file."""
    import yaml
    
    with open(config_path, 'r') as f:
        if config_path.endswith('.yaml') or config_path.endswith('.yml'):
            return yaml.safe_load(f)
        elif config_path.endswith('.json'):
            return json.load(f)
        else:
            raise ValueError(f"Unsupported config format: {config_path}")


def save_config(config: Dict[str, Any], config_path: str) -> None:
    """Save configuration to a YAML or JSON file."""
    import yaml
    
    with open(config_path, 'w') as f:
        if config_path.endswith('.yaml') or config_path.endswith('.yml'):
            yaml.dump(config, f, default_flow_style=False)
        elif config_path.endswith('.json'):
            json.dump(config, f, indent=2)
        else:
            raise ValueError(f"Unsupported config format: {config_path}")


# =============================================================================
# Demo and Example Utilities
# =============================================================================

def print_section(title: str, char: str = "=") -> None:
    """Print a formatted section header."""
    line = char * 60
    print(f"\n{line}")
    print(f"  {title}")
    print(f"{line}\n")


def print_twin_state(state: TwinState) -> None:
    """Pretty print a twin state."""
    print(f"Twin ID: {state.twin_id}")
    print(f"Status: {state.status}")
    print(f"Health Score: {state.health_score:.2%}")
    print(f"Last Updated: {state.timestamp}")
    print("Properties:")
    for key, value in state.properties.items():
        print(f"  - {key}: {value}")


def run_demo(demo_func: Callable, title: str) -> None:
    """Run a demo function with formatted output."""
    print_section(title)
    try:
        demo_func()
        print("\n[Demo completed successfully]")
    except Exception as e:
        print(f"\n[Demo failed with error: {e}]")
        raise


# =============================================================================
# ID Generation
# =============================================================================

def generate_id(prefix: str = "DT") -> str:
    """Generate a unique ID for twins, sensors, or alerts."""
    timestamp = int(time.time() * 1000)
    random_part = random.randint(1000, 9999)
    return f"{prefix}-{timestamp}-{random_part}"


if __name__ == "__main__":
    # Quick test of utilities
    print_section("DualTwin Utilities Test")
    
    # Test sensor simulator
    simulator = SensorSimulator("TEMP-001", base_value=25.0, unit="°C")
    readings = simulator.generate_stream(10)
    print(f"Generated {len(readings)} sensor readings")
    
    # Test statistics
    values = [r.value for r in readings]
    stats = calculate_statistics(values)
    print(f"Statistics: {stats}")
    
    # Test twin state
    state = TwinState(
        twin_id=generate_id("TWIN"),
        timestamp=datetime.now(),
        properties={"temperature": 25.0, "pressure": 101.3}
    )
    print_twin_state(state)
    
    print("\n[All tests passed]")
